# Generated by Django 5.0.1 on 2024-04-01 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('Phone_Numder', models.CharField(max_length=11)),
                ('Login', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=25)),
                ('Massanger', models.CharField(max_length=255)),
                ('Photo_Profile', models.ImageField(upload_to='')),
                ('Jwt_Token', models.UUIDField(unique=True)),
                ('Tarife', models.CharField(max_length=255)),
                ('Tarif_Active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Tg_Id', models.CharField(max_length=255)),
                ('Parameters', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Newness_Category',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tarife',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Created_Date', models.DateTimeField()),
                ('User_Uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyticapi.client')),
            ],
        ),
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Url', models.CharField(max_length=255)),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyticapi.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='Referal_Url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyticapi.referal'),
        ),
        migrations.CreateModel(
            name='StackOverflow',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Created_Date', models.DateTimeField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyticapi.newness_category')),
                ('User_Uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyticapi.client')),
            ],
        ),
    ]
