# Generated by Django 5.0.4 on 2024-04-24 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyticapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referal',
            name='User_Id',
        ),
    ]
