# Generated by Django 5.0.4 on 2024-04-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticapi', '0002_remove_referal_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Phone_Numder',
            field=models.CharField(max_length=255),
        ),
    ]
