# Generated by Django 5.0.4 on 2024-04-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticapi', '0003_alter_client_phone_numder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=100)),
                ('messages_count', models.IntegerField(default=0)),
                ('keyword_matches', models.IntegerField(default=0)),
                ('relevance', models.FloatField(default=0)),
            ],
        ),
    ]
