# Generated by Django 5.0.4 on 2024-05-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticapi', '0005_alter_client_referal_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='members_count',
            field=models.IntegerField(default=0),
        ),
    ]
